[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 9600
lib_deps = 
	majicdesigns/MD_Parola@^3.7.1
	majicdesigns/MD_MAX72XX@^3.5.1
	ottowinter/ESPAsyncWebServer-esphome@^3.1.0
	bblanchon/ArduinoJson@^7.0.2
	bblanchon/StreamUtils@^1.8.0